version: '2.2'
services:

  postgres:
    container_name: event-postgis
  
  geoserver:
    container_name: event-geoserver

  proxy:
      image: nginx
      container_name: event-proxy
      volumes:
        - ./geoserver.conf:/etc/nginx/conf.d/default.conf:rw
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      ports:
        - "443:443"
        - "80:80"
      depends_on:
        - geoserver  
  
  certbot:
      image: certbot/certbot
      volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"